name: flutter_movie_app
description: Movies Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
